### ISSUE TITLE
Buckets Pop-up

### ISSUE THREAD

**Issue by dylrob34** [dylrob34/toDo#15]
Add buckets with edit icons to buckets pop-up

**Comment by Cknutson100** [comment]
@dylrob34 I think we might need to re-work this problem. since we have a different structure right now on Buckets/Pop-ups than we do with Tasks. Right now our "Task.jsx" component is being sent to "Tasks.jsx" where it's being packaged up and set to be rendered. Unfortunately, the bucket pop-up feature uses the generic pop-up component and then re-maps our buckets and their index in it as children. So we when I want to edit a specific bucket, I'll have to pass the specific index with the specific edit icon that was pressed. 
I don't know how to do that yet so I'll have to research.

**Comment by Cknutson100** [comment]
@dylrob34 @Cknutson100 CK left a number of comments in Buckets.jsx this comment is so that he doesn't forget to fix the questions he had.
